/********************************************************************
* CCDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CCDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCCDict();
extern void G__cpp_setup_inheritanceCCDict();
extern void G__cpp_setup_typetableCCDict();
extern void G__cpp_setup_memvarCCDict();
extern void G__cpp_setup_globalCCDict();
extern void G__cpp_setup_memfuncCCDict();
extern void G__cpp_setup_funcCCDict();
extern void G__set_cpp_environmentCCDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DefineCC.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CCDictLN_TClass;
extern G__linked_taginfo G__CCDictLN_TBuffer;
extern G__linked_taginfo G__CCDictLN_TMemberInspector;
extern G__linked_taginfo G__CCDictLN_TObject;
extern G__linked_taginfo G__CCDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CCDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CCDictLN_TList;
extern G__linked_taginfo G__CCDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CCDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CCDictLN_TQObject;
extern G__linked_taginfo G__CCDictLN_TQObjSender;
extern G__linked_taginfo G__CCDictLN_TGObject;
extern G__linked_taginfo G__CCDictLN_TGWindow;
extern G__linked_taginfo G__CCDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__CCDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__CCDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CCDictLN_TGFrame;
extern G__linked_taginfo G__CCDictLN_TGCompositeFrame;
extern G__linked_taginfo G__CCDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__CCDictLN_TGMainFrame;
extern G__linked_taginfo G__CCDictLN_TGTransientFrame;
extern G__linked_taginfo G__CCDictLN_TGTab;
extern G__linked_taginfo G__CCDictLN_TGNumberEntry;
extern G__linked_taginfo G__CCDictLN_guiInfo;
extern G__linked_taginfo G__CCDictLN_DefineCC;

/* STUB derived class for protected member access */
