/********************************************************************
* SchrodyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SchrodyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSchrodyDict();
extern void G__cpp_setup_inheritanceSchrodyDict();
extern void G__cpp_setup_typetableSchrodyDict();
extern void G__cpp_setup_memvarSchrodyDict();
extern void G__cpp_setup_globalSchrodyDict();
extern void G__cpp_setup_memfuncSchrodyDict();
extern void G__cpp_setup_funcSchrodyDict();
extern void G__set_cpp_environmentSchrodyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Schrody.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SchrodyDictLN_TClass;
extern G__linked_taginfo G__SchrodyDictLN_TBuffer;
extern G__linked_taginfo G__SchrodyDictLN_TMemberInspector;
extern G__linked_taginfo G__SchrodyDictLN_TObject;
extern G__linked_taginfo G__SchrodyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SchrodyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SchrodyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SchrodyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SchrodyDictLN_TQObject;
extern G__linked_taginfo G__SchrodyDictLN_TGObject;
extern G__linked_taginfo G__SchrodyDictLN_TGWindow;
extern G__linked_taginfo G__SchrodyDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__SchrodyDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SchrodyDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SchrodyDictLN_TGFrame;
extern G__linked_taginfo G__SchrodyDictLN_TGCompositeFrame;
extern G__linked_taginfo G__SchrodyDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SchrodyDictLN_TGTextButton;
extern G__linked_taginfo G__SchrodyDictLN_TGMainFrame;
extern G__linked_taginfo G__SchrodyDictLN_TGNumberEntry;
extern G__linked_taginfo G__SchrodyDictLN_guiInfo;
extern G__linked_taginfo G__SchrodyDictLN_DefineCC;
extern G__linked_taginfo G__SchrodyDictLN_TGComboBox;
extern G__linked_taginfo G__SchrodyDictLN_Schrody;

/* STUB derived class for protected member access */
