/********************************************************************
* GuiPDEDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GuiPDEDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGuiPDEDict();
extern void G__cpp_setup_inheritanceGuiPDEDict();
extern void G__cpp_setup_typetableGuiPDEDict();
extern void G__cpp_setup_memvarGuiPDEDict();
extern void G__cpp_setup_globalGuiPDEDict();
extern void G__cpp_setup_memfuncGuiPDEDict();
extern void G__cpp_setup_funcGuiPDEDict();
extern void G__set_cpp_environmentGuiPDEDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GuiPDE.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GuiPDEDictLN_TClass;
extern G__linked_taginfo G__GuiPDEDictLN_TBuffer;
extern G__linked_taginfo G__GuiPDEDictLN_TMemberInspector;
extern G__linked_taginfo G__GuiPDEDictLN_TObject;
extern G__linked_taginfo G__GuiPDEDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GuiPDEDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiPDEDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GuiPDEDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiPDEDictLN_TGObject;
extern G__linked_taginfo G__GuiPDEDictLN_TQObject;
extern G__linked_taginfo G__GuiPDEDictLN_TGWindow;
extern G__linked_taginfo G__GuiPDEDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GuiPDEDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GuiPDEDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GuiPDEDictLN_TGFrame;
extern G__linked_taginfo G__GuiPDEDictLN_TGCompositeFrame;
extern G__linked_taginfo G__GuiPDEDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GuiPDEDictLN_TGTextButton;
extern G__linked_taginfo G__GuiPDEDictLN_TGMainFrame;
extern G__linked_taginfo G__GuiPDEDictLN_TGButtonGroup;
extern G__linked_taginfo G__GuiPDEDictLN_TGRadioButton;
extern G__linked_taginfo G__GuiPDEDictLN_TGNumberEntry;
extern G__linked_taginfo G__GuiPDEDictLN_TCanvas;
extern G__linked_taginfo G__GuiPDEDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__GuiPDEDictLN_TGVProgressBar;
extern G__linked_taginfo G__GuiPDEDictLN_PDECond;
extern G__linked_taginfo G__GuiPDEDictLN_TGStatusBar;
extern G__linked_taginfo G__GuiPDEDictLN_TGraph2D;
extern G__linked_taginfo G__GuiPDEDictLN_PDEGui;

/* STUB derived class for protected member access */
